travis:
  secure:
    BINSTAR_TOKEN: ZSe8QsZEvGZ3rEze7RTJssUyKxamzgOLKlvi0jr0KMitK/9brOW6HUrC74QBDQVB+ETm74H2nD8xrorIg/ufzY+gZCmBfk3KqqcR4eJcApDLlkfpuSY8GeRhYsBlu05laderYkvy0OuQ1RM/dfHMZfxA27X5/4LyCJcTJi9H94dy88UdZkWhdjMgen9LU2dVPX1XCml3zUx4DSMKs+TFTj0LoBJc0jGnQlDNNc1f+fv4z6HR0hP480sJkB1QG7oU7gky+pgdw/CgvfdOZlOUJ9qmpmD4E0ci0K+NWTvhh2SvKFKbvxAMGEItTWe4YRaDGdr3TziaQ4JPqTBxm6wg46k/yo2IY1n10/OBkPDZM+sUU0JML4G2hRdtcglcTcRc8bn8J2HX9595WVvxK14GYaR5o5+zJf5GiVDYi4p4kEXo0NCNSp38x2a+ytexAJ8X6HWoyVA+j99+hIcGYJU6B7nriev1EQhBkoXxMyDNRvi7AytCvJ2FkxFWO88HEQo6SJVXBzUBJQ3GB2SyL3hpbV1HJW6XGF3l2YjTkcLBpXlGehflW3UsvbOnrZt/98PIfGrC4XRI9K1ISVZ0iNXyI0i/9fwABe2Vfe4U1EX+G1CgkNkiG6PCUKbNS3W3J65YIKyLj3BkTVjW2EJBbVpsFVSpNAfvdPxe2sA/mmlpULk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
